version: '3'

services:

  backend:
    # tty: true
    image: backend_portfolio

    build: 
      context: ..
      dockerfile: docker/Dockerfile
      
    volumes: 
      - '..:/var/www/html'
    ports:
      - 127.0.0.1:8080:80

volumes:
    database:
