version: '3'

services:

  backend:
    # tty: true
    image: backend_portfolio

    build: 
      context: ../docker
      dockerfile: Dockerfile
      
    volumes: 
      - '..:/var/www/html'
    ports:
      - 80:80

volumes:
    database: